language: php

dist: trusty

php:
  - 7.2
  - 7.3

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION="4.3.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.4.*"
    - php: 7.4snapshot
      env: SYMFONY_VERSION="4.4.*"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - echo memory_limit = -1 >> $INI_FILE

install:
  - composer install

script:
  - vendor/bin/phpunit
